FINANCIAL_MONTH_PAGE_ID = "ecc237c39382476e8cefc7224ca5f87c"

ACT_MONTH_NOTION_PROPERTY = "Mês atual"
TOTAL_NOTION_PROPERTY = "Valor Investido"
TOTAL_NOW_NOTION_PROPERTY = "Valor Atual"

TOTAL_INCOMING_NOTION_PROPERTY = "Total Ganhos"
TOTAL_OUTCOMING_NOTION_PROPERTY = "Total Gastos"
TOTAL_INVESTMENTS_NOTION_PROPERTY = "Total Investimentos"

# FUNDAMENTUS FIIs

FUNDAMENTUS_FIIS_PAGE_ID = "3df91f697e204972bcdbe875ef0f9260"
FUNDAMENTUS_FII_NAME_NOTION_PROPERTY = "Name"
FUNDAMENTUS_FII_SEGMENT_NOTION_PROPERTY = 'Segmento'
FUNDAMENTUS_FII_PRICE_NOTION_PROPERTY = 'Price'
FUNDAMENTUS_FII_VP_COTA_NOTION_PROPERTY = 'VP_COTA'
FUNDAMENTUS_FII_PVP_NOTION_PROPERTY = 'PVP'
FUNDAMENTUS_FII_DY_NOTION_PROPERTY = 'DY'

# REPORT FIIs

REPORT_FIIS_PAGE_ID = "7f19466396af4cf08189b98b28df142a"
REPORT_FII_NAME_NOTION_PROPERTY = "Código"
REPORT_FII_SEGMENT_NOTION_PROPERTY = 'Segmento'
REPORT_FII_PRICE_NOTION_PROPERTY = 'Preço'
REPORT_FII_PVP_NOTION_PROPERTY = 'P/VP'
REPORT_FII_DY_NOTION_PROPERTY = 'DY'

# FUNDAMENTUS STOCKs

FUNDAMENTUS_STOCKS_PAGE_ID = "6049e454d00e48b7ab206c77a1a60c93"
FUNDAMENTUS_STOCK_NAME_NOTION_PROPERTY = "Name"
FUNDAMENTUS_STOCK_SECTOR_NOTION_PROPERTY = 'Setor'
FUNDAMENTUS_STOCK_PRICE_NOTION_PROPERTY = 'Price'
FUNDAMENTUS_STOCK_PVP_NOTION_PROPERTY = 'PVP'
FUNDAMENTUS_STOCK_PL_NOTION_PROPERTY = 'PL'
FUNDAMENTUS_STOCK_DY_NOTION_PROPERTY = 'DY'

# REPORT STOCKs

REPORT_STOCKS_PAGE_ID = "ceae4d226bef41e9a01efa9f1c4ec722"
REPORT_STOCK_NAME_NOTION_PROPERTY = "Código"
REPORT_STOCK_SECTOR_NOTION_PROPERTY = 'Setor'
REPORT_STOCK_PRICE_NOTION_PROPERTY = 'Preço'
REPORT_STOCK_PVP_NOTION_PROPERTY = 'PVP'
REPORT_STOCK_PL_NOTION_PROPERTY = 'PL'
REPORT_STOCK_DY_NOTION_PROPERTY = 'DY'

# FUNDAMENTUS BDR

BDRS_PAGE_ID = "d1042292eba84cc7abfe3ecc1281fab4"
BDR_NAME_NOTION_PROPERTY = "Name"
BDR_SECTOR_NOTION_PROPERTY = 'Setor'
BDR_PRICE_NOTION_PROPERTY = 'Price'
BDR_PVP_NOTION_PROPERTY = 'PVP'
BDR_PL_NOTION_PROPERTY = 'PL'
BDR_DY_NOTION_PROPERTY = 'DY'