FINANCIAL_MONTH_PAGE_ID = "ecc237c39382476e8cefc7224ca5f87c"

ACT_MONTH_NOTION_PROPERTY = "Mês atual"
TOTAL_NOTION_PROPERTY = "Valor Investido"
TOTAL_NOW_NOTION_PROPERTY = "Valor Atual"

TOTAL_INCOMING_NOTION_PROPERTY = "Total Ganhos"
TOTAL_OUTCOMING_NOTION_PROPERTY = "Total Gastos"
TOTAL_INVESTMENTS_NOTION_PROPERTY = "Total Investimentos"

# FUNDAMENTUS FIIs

FIIS_PAGE_ID = "3df91f697e204972bcdbe875ef0f9260"
FII_NAME_NOTION_PROPERTY = "Name"
FII_SEGMENT_NOTION_PROPERTY = 'Segmento'
FII_PRICE_NOTION_PROPERTY = 'Price'
FII_VP_COTA_NOTION_PROPERTY = 'VP_COTA'
FII_PVP_NOTION_PROPERTY = 'PVP'
FII_DY_NOTION_PROPERTY = 'DY'

# FUNDAMENTUS STOCKs

STOCKS_PAGE_ID = "6049e454d00e48b7ab206c77a1a60c93"
STOCK_NAME_NOTION_PROPERTY = "Name"
STOCK_SECTOR_NOTION_PROPERTY = 'Setor'
STOCK_PRICE_NOTION_PROPERTY = 'Price'
STOCK_PVP_NOTION_PROPERTY = 'PVP'
STOCK_PL_NOTION_PROPERTY = 'PL'
STOCK_DY_NOTION_PROPERTY = 'DY'

# FUNDAMENTUS BDR

BDRS_PAGE_ID = "d1042292eba84cc7abfe3ecc1281fab4"
BDR_NAME_NOTION_PROPERTY = "Name"
BDR_SECTOR_NOTION_PROPERTY = 'Setor'
BDR_PRICE_NOTION_PROPERTY = 'Price'
BDR_PVP_NOTION_PROPERTY = 'PVP'
BDR_PL_NOTION_PROPERTY = 'PL'
BDR_DY_NOTION_PROPERTY = 'DY'