FINANCIAL_MONTH_PAGE_ID = "ecc237c39382476e8cefc7224ca5f87c"
FIIS_PAGE_ID = "3df91f697e204972bcdbe875ef0f9260"

ACT_MONTH_NOTION_PROPERTY = "Mês atual"
TOTAL_NOTION_PROPERTY = "Valor Investido"
TOTAL_NOW_NOTION_PROPERTY = "Valor Atual"

TOTAL_INCOMING_NOTION_PROPERTY = "Total Ganhos"
TOTAL_OUTCOMING_NOTION_PROPERTY = "Total Gastos"
TOTAL_INVESTMENTS_NOTION_PROPERTY = "Total Investimentos"

FII_NAME_NOTION_PROPERTY = "Name"