NOTION_PROJECT_PAGE_ID = "24869af463b34b879fd9572e7029641f"

TASKS_TITLE_NOTION_PROPERTY = "Tarefas"
TASKS_PROJECT_NOTION_PROPERTY = "Projeto"
TASKS_NAME_NOTION_PROPERTY = "Nome"
TASKS_STATUS_NOTION_PROPERTY = "Status"

# Status
DONE_STATUS = "Done"
PLANNING_STATUS = "Planning"
ARCHIVED_STATUS = "Arquivado"
IN_PROGRESS_STATUS = "In Progress"
BLOCKED_STATUS = "Blocked"
THIS_WEEK_STATUS = "This week"
SPRINT_STATUS = "Sprint"