name: Chatbot

on:
  workflow_dispatch:
  repository_dispatch:
    types: [chatbot]

jobs:
  #log-info:
  update_data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repositório..
        uses: actions/checkout@v3

      - name: Instalando dependências..
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          pip3 install pyTelegramBotAPI

      - name: Enviando notificaçao por Telegram 
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_BOT_ID }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: Bot online!
          disable_notification: true

      - name: Configurando variaveis de ambiente..
        run: |
          echo "TELEGRAM_BOT_TOKEN=${{ secrets.TELEGRAM_TOKEN }}" >> $GITHUB_ENV

      - name: Inicializando Chat Bot
        run: python3 chatbot.py

      - name: Enviando notificaçao por Telegram 
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_BOT_ID }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: Bot offline!
          disable_notification: true
