name: Check Currency

on:
  workflow_dispatch:

  #push:
    #branches:
    #  - master
    #  - 'feature/*'
    #  - '!dev'
    #branches-ignore:
    #  - dev
  schedule:
    - cron: "0 7 * * *" # www.crontab.guru

jobs:
  update_data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repositório..
        uses: actions/checkout@v3

      - name: Instalando dependências..
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          pip3 install gspread oauth2client
          pip3 install notion-client
          
      - id: 'auth'
        name: Autenticando no Google Cloud..
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: ${{ secrets.GOOGLE_SERVICE_KEY }}

      - name: Configurando variaveis de ambiente..
        run: |
          echo "GOOGLE_CLOUD_CREDENTIALS_FILE=${{ steps.auth.outputs.credentials_file_path }}" >> $GITHUB_ENV
  
      - name: Consultando infos em Google Sheets (multiple lines)
        run: |
          echo 'RESULT<<EOF' >> $GITHUB_ENV
          python3 check_currency.py >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV

      - name: Enviando notificaçao por Telegram 
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_BOT_ID }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: ${{ env.RESULT }}
          disable_notification: true
