name: Daily Report

on:
  workflow_dispatch:
  schedule:
    - cron: "0 9 * * *" # www.crontab.guru

jobs:
  update_data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repositório..
        uses: actions/checkout@v3

      - name: Instalando dependências..
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          pip3 install notion-client
          pip3 install pyTelegramBotAPI
          
      - name: Configurando variaveis de ambiente..
        run: |
          echo "NOTION_TOKEN=${{ secrets.NOTION_TOKEN }}" >> $GITHUB_ENV
          echo "TELEGRAM_BOT_TOKEN=${{ secrets.TELEGRAM_TOKEN }}" >> $GITHUB_ENV

      - name: Consultando Daily Report em Notion
        run: python3 daily_report.py 