name: Daily Reporter

on:
  workflow_dispatch:

  #push:
    #branches:
    #  - master
    #  - 'feature/*'
    #  - '!dev'
    #branches-ignore:
    #  - dev
  schedule:
    - cron: "0 7 * * *" # www.crontab.guru

jobs:
  update_data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repositório..
        uses: actions/checkout@v3

      - name: Instalando dependências..
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          pip3 install notion-client
          
      - name: Configurando variaveis de ambiente..
        run: |
          echo "NOTION_TOKEN=${{ secrets.NOTION_TOKEN }}" >> $GITHUB_ENV

      - name: Consultando infos em Notion
        id: consulta_notion
        run: |
          python3 daily_report.py
          echo "::set-output name=daily_report_result::$(cat daily_report_output.txt)"

      - name: Enviando notificaçao por Telegram 
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_BOT_ID }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: ${{ steps.consulta_notion.outputs.daily_report_result }}
          disable_notification: true
