name: GitHub Actions Class

on: 
  repository_dispatch:
    types: [build]

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: Echo Payload
        run: echo ${{ github.client_payload.env }}
