name: Atualização de Cotaçao

on:
  push:
    branches:
      - master
    #branches-ignore:
    #  - dev
#schedule:
    #- cron: "30 12,15,18,21 * * 1-5" # www.crontab.guru

jobs:
  update_data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repositório..
        uses: actions/checkout@v3

      - name: Instalando dependências..
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          pip3 install notion-client
          
      - name: Configurando variaveis de ambiente..
        run: |
          echo "NOTION_TOKEN=${{ secrets.NOTION_TOKEN }}" >> $GITHUB_ENV

      - name: Atualizando em Notion
        run: python3 check_birthday.py

      - name: Enviando notificaçao por Telegram 
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_BOT_ID }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: Check aniversarios executado
          disable_notification: true
