name: Update de Fundamentus

on:
  workflow_dispatch:
  schedule:
    - cron: "0 1 * * 0" # www.crontab.guru

jobs:
  update_data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repositório..
        uses: actions/checkout@v3

      - name: Instalando dependências..
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          pip3 install notion-client
          pip3 install pandas
          pip3 install lxml

      - name: Configurando variaveis de ambiente..
        run: |
          echo "NOTION_TOKEN=${{ secrets.NOTION_TOKEN }}" >> $GITHUB_ENV

      - name: Stocks - Atualizando Notion Fundamentus
        run: python3 update_stocks.py

      - name: Fiis - Atualizando Notion Fundamentus
        run: python3 update_fiis.py

      - name: Enviando notificaçao por Telegram 
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_BOT_ID }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: '👍🏼 Fundamentus atualizado!' 
          disable_notification: true
